### ISSUE TITLE
Site layout

### ISSUE THREAD

**Issue by ocefpaf** [pyoceans/seapy#4]
I need you opinion  @juoceano.  The [current layout](http://ocefpaf.github.io/seapy/):

![current](https://cloud.githubusercontent.com/assets/950575/6845388/07bbaf0e-d393-11e4-9ca2-d9b2c4ed21f5.png)

or this,

![alternative](https://cloud.githubusercontent.com/assets/950575/6845389/0984c56e-d393-11e4-8dac-34963bb6e7e7.png)

**Comment by juoceano** [comment]
Definitivamente o segundo. Mas eu colocaria outro tom de azul no texto que esta na caixa a esquerda. 
:_\//:

**Comment by ocefpaf** [comment]
I will think about this a little longer...  The default theme has better support for the yaml variables than the custom one.
