### ISSUE TITLE
Dead links on homepage

### ISSUE THREAD

**Issue by andrew-s28** [pyoceans/seapy#44]
I was just introduced to the [sea-py site](https://pyoceans.github.io/sea-py/) as a place [to potentially contribute a project](https://github.com/andrew-s28/COARE-algorithm), but looking through it I noticed there are quite a few dead links on the main page, some from major packages (e.g., numpy).

Is there still interest in the community to maintain this site? I would be happy to submit some pull requests to fix some of the links if so.

**Comment by ocefpaf** [comment]
> Is there still interest in the community to maintain this site? I would be happy to submit some pull requests to fix some of the links if so.

You can send a PR and, if you want, I can add you as a maintainer here so you can merge other PRs in the near future. I have to confess that I do't have enough time to keep this up to date as I used to. Any help is very welcomed!

**Comment by andrew-s28** [comment]
Sounds great, I think it is a useful project, so would be happy to be added as a maintainer. Thanks!
